ERROR 2020-12-05 12:13:26,591 root : Сервер недоступний
ERROR 2020-12-05 12:13:26,591 root : Помилка: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02FEA4F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR 2020-12-05 12:14:28,597 root : Сервер недоступний
ERROR 2020-12-05 12:14:28,597 root : Помилка: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02FEA910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR 2020-12-05 12:15:30,604 root : Сервер недоступний
ERROR 2020-12-05 12:15:30,604 root : Помилка: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02FEAD00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR 2020-12-05 12:16:32,621 root : Сервер недоступний
ERROR 2020-12-05 12:16:32,622 root : Помилка: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03010118>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
